### ISSUE TITLE
`GETTEXT_PATH` handled improperly

### ISSUE THREAD

**Issue by rutgerbrf** [Kalimehtar/free-gettext#1]
Hello! First issue :)

When the `GETTEXT_PATH` environment variable is configured, its value is not actually used; internally, the library then configures the lookup path to be `":"`, as `string-split` is not actually called here:
https://github.com/Kalimehtar/free-gettext/blob/c7ef1a8567e284108d8620198c98a49ccab5b7b8/main.rkt#L724-L727

This issue is fixed by changing `(λ (x) string-split x ":")` to `(λ (x) (string-split x ":"))`

**Comment by Kalimehtar** [comment]
Thank you! Fixed.
